[package]
name = "builddepfaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#deb822-lossless = "0.1.23"
deb822-fast = { path = "deb822-fast" }
unicase = "2.7.0"
